### PR TITLE
Added my own UI Card

### PR DESCRIPTION
**Pull request by akshit5565**

### CODE REVIEW

**Comment by vibgyor786** [comment]
uicard
can you allign this , all other components are looking good

**Comment by akshit5565** [comment]
> uicard can you allign this , all other components are looking good

@vibgyor786 Sure, doing it right now!!

**Comment by akshit5565** [comment]
@vibgyor786 Sir it is perfectly alligned on my screen, plz do check where the issue is.
Thank you !!

**Comment by vibgyor786** [comment]
@akshit5565 try to make it more responsive , you can use flex box

**Comment by akshit5565** [comment]
@vibgyor786  I have made the required changes , please do check and give me the hacktoberfest-accepted label.
Thank you so much sir !!

**Comment by akshit5565** [comment]
> @akshit5565 add your name in contributors section of readme.md , then i will accept your pr

@vibgyor786  Done sir

**Comment by vibgyor786** [comment]
@akshit5565 merging your pr , thanks for the contribution .

**Pull request merged**
